# Makefile for generating the PDF file.

all:
	latexmk -r latexmkrc

clean:
	rm -rf *.aux *.lof *.log *.lot *.fls *.out *.toc *.fmt *.fot *.cb *.cb2 .*.lb
	rm -rf *.dvi *.xdv *-converted-to.* *.pdf
	rm -rf *latexmk
